Repository depromeet/10mm-client-web, pull requests merged in 2023-12, with the labels that each got.

#64 [Fix] Storybook build error fix
  .storybook/preview.ts
  src/components/Layout/Header.stories.ts
Labels: hotfix

#72 Button Component 구현
  src/app/globals.css
  src/app/select/SelectMissionForm.tsx
  src/components/Button.tsx
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  src/styles/color.ts
Labels: style, design

#73 PR 템플릿 수정
  .github/pull_request_template.md
Labels: enhancement

#74 🚑️ button disabled 되면 클릭 안되게 수정
  src/app/globals.css
Labels: bug fix

#82 Stopwatch View 구현
  public/assets/stopwatch/disabled-circle.png
  public/assets/stopwatch/disabled-small-circle.svg
  public/assets/stopwatch/gradient-circle.png
  public/assets/stopwatch/small-circle.svg
  src/app/layout.tsx
  src/app/timer/layout.tsx
  src/app/timer/page.tsx
  src/app/timer/useTimer.ts
  src/components/Button/Button.tsx
  src/components/Layout/Header.tsx
  src/components/Stopwatch/Stopwatch.stories.tsx
  src/components/Stopwatch/Stopwatch.tsx
  src/styled-system/tokens/keyframes.css
  src/styled-system/tokens/tokens.d.ts
  src/styles/motion.ts
Labels: feature, style

#96 Feat/button design system
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
Labels: design

#100 [Design] Header Component 구현
  src/app/select/page.tsx
  src/app/stopwatch/layout.tsx
  src/components/Header/Header.stories.tsx
  src/components/Header/Header.tsx
  src/components/Header/IconHeader.tsx
  src/components/Header/NoneHeader.tsx
  src/components/Header/TextButtonHeader.tsx
  src/components/Header/index.tsx
  src/components/Layout/Header.stories.ts
  src/components/Layout/Header.tsx
Labels: design

#105 :art: 메인 이미지 교체
  public/images/login_bg.png
  src/app/page.tsx
Labels: design

#109 [FIX] 미션등록페이지 버튼 css 수정
  src/components/Button/Button.tsx
Labels: design

#104 [FEAT] 모니터링을 위한 믹스패널 , gtag 설정
  .pnp.cjs
  .yarn/cache/@types-gtag.js-npm-0.0.18-dbe2f5d9eb-194c11f7c7.zip
  .yarn/cache/@types-mixpanel-browser-npm-2.47.5-29fd891527-57f196a07d.zip
  .yarn/cache/mixpanel-browser-npm-2.48.1-941aca78bf-5dc47218cf.zip
  package.json
  src/app/certification/page.tsx
  src/app/page.tsx
  src/app/select/CheckCircleIcon.tsx
  src/app/select/SelectMissionForm.tsx
  src/app/stopwatch/page.tsx
  src/components/Header/Header.tsx
  src/components/MonitoringInitializer.tsx
  src/utils/common.ts
  src/utils/event/gtag.ts
  src/utils/event/index.ts
  src/utils/index.ts
  yarn.lock
Labels: feature

#110 [Design] Bottom Sheet Component 구현
  src/components/BottomSheet/BottomSheet.stories.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Header/Header.tsx
Labels: design

#116 :art: 버튼 css 수정
  src/components/Button/Button.tsx
Labels: design

#117 :art: 파비콘수정
  src/app/favicon.ico
Labels: design

#119 :art: OgImage 수정
  public/og-image.png
  src/app/layout.tsx
Labels: design

#120 [Task] 미션 등록 페이지에서 입력한 카테고리 타이머에서 보여주기
  src/app/select/MissionRegistration.tsx
  src/app/stopwatch/page.tsx
Labels: feature

#122 🚑️ stopwatch overflow 해결
  src/app/stopwatch/page.tsx
Labels: bug fix, design

#133 :lipstick: 카테고리 placeholder
  src/app/select/MissionRegistration.tsx
Labels: design

#138 :art: 스토리북 폴더 구조 변경
  src/components/BottomSheet/BottomSheet.stories.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Layout/Header.stories.ts
  src/components/Layout/Header.tsx
  src/styles/color.stories.mdx
Labels: docs, design

#142 Design/color theme
  src/app/certification/page.tsx
  src/app/complete/page.tsx
  src/app/select/MissionRegistration.tsx
  src/app/stopwatch/page.tsx
  src/components/Dialog/DefaultDialog.tsx
  src/components/Input/Input.tsx
  src/components/Stopwatch/Stopwatch.tsx
  src/styled-system/tokens/index.css
  src/styled-system/tokens/index.mjs
  src/styled-system/tokens/tokens.d.ts
  src/styled-system/types/prop-type.d.ts
  src/styles/color.ts
  src/styles/typography.ts
Labels: design

#139 :art: App폴더 하위 디렉토리 구조 변경
  src/app/mission/[id]/record/layout.tsx
  src/app/mission/[id]/record/page.tsx
  src/app/mission/[id]/stopwatch/layout.tsx
  src/app/mission/[id]/stopwatch/page.tsx
  src/app/mission/[id]/stopwatch/useStopwatch.ts
  src/app/mission/[id]/stopwatch/useStopwatchStatus.ts
  src/app/mission/new/CategoryBottomSheet.tsx
  src/app/mission/new/MissionRegistration.tsx
  src/app/mission/new/PublicBottomSheet.tsx
  src/app/mission/new/RadioInputWithImg.tsx
  src/app/mission/new/SelectMissionForm.tsx
  src/app/mission/new/layout.tsx
  src/app/mission/new/page.tsx
  src/app/mission/new/select.constants.ts
  src/app/mission/success/layout.tsx
  src/app/mission/success/page.tsx
  src/app/page.tsx
  src/constants/router.ts
Labels: enhancement

#187 Task/axios instance setting
  .pnp.cjs
  .yarn/cache/@tanstack-query-core-npm-4.36.1-7594b7a096-7c648872cd.zip
  .yarn/cache/@tanstack-query-core-npm-5.14.2-73bc9099f9-089ea0f825.zip
  .yarn/cache/@tanstack-react-query-npm-4.36.1-435eddf619-764b860c3a.zip
  .yarn/cache/@tanstack-react-query-npm-5.14.6-8104c750d1-4b47abde7f.zip
  .yarn/cache/axios-npm-1.6.2-2334cb6eee-612bc93f8f.zip
  .yarn/cache/follow-redirects-npm-1.15.3-ca69c47b72-60d98693f4.zip
  .yarn/cache/use-sync-external-store-npm-1.2.0-44f75d2564-a676216aff.zip
  package.json
  src/apis/index.ts
  src/apis/instance.api.ts
  src/apis/post.ts
  yarn.lock
Labels: enhancement

#189 :art: 닉네임페이지 ui 작업
  src/app/auth/nickname/page.tsx
Labels: design

#188 [Design] appbar-bottom (navigation) 컴포넌트 추가
  panda.config.ts
  src/components/AppBarBottom/AppBarBottom.stories.tsx
  src/components/AppBarBottom/AppBarBottom.tsx
  src/components/AppBarBottom/AppBarBottomVIew.tsx
  src/constants/navigation.ts
  src/constants/router.ts
  src/styled-system/tokens/index.css
  src/styled-system/tokens/index.mjs
  src/styled-system/tokens/tokens.d.ts
Labels: design

#197 🎨 Stopwatch > 1차 MVP 화면에서 변경된 부분 수정
  src/components/Icon/LightningIcon.tsx
  src/components/Icon/TENMMSymbolIcon.tsx
  src/components/Icon/index.tsx
  src/components/Stopwatch/Stopwatch.tsx
Labels: style, design

#192 :art: LoginPage 디자인 추가
  public/images/login_bg.png
  src/app/auth/login/page.tsx
  src/components/ButtonSocialLogin/ButtonSocialLogin.stories.tsx
  src/components/ButtonSocialLogin/ButtonSocialLogin.tsx
  src/components/Icon/AppleLoginIcon.tsx
  src/components/Icon/KakaoLoginIcon.tsx
  src/components/Icon/index.tsx
Labels: design

#191 [Design] Thumbnail component 구현
  public/images/thumbnail-null.png
  public/images/thumbnail-test.png
  src/components/Thumbnail/Thumbnail.mdx
  src/components/Thumbnail/Thumbnail.stories.ts
  src/components/Thumbnail/Thumbnail.tsx
  src/components/Thumbnail/Thumbnail.types.ts
Labels: docs, design

#194 🎨 Empty component 추가
  public/images/empty-celebratory.png
  public/images/empty-docs.png
  src/components/Empty/Empty.stories.tsx
  src/components/Empty/Empty.tsx
  src/components/Empty/Empty.types.ts
  src/components/Icon/RefreshIcon.tsx
  src/components/Icon/index.tsx
Labels: design

#196 :art: Badge 컴포넌트 추가
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/Badge.tsx
Labels: design

#190 [Task] hotjar 모니터링 세팅
  .pnp.cjs
  .yarn/cache/react-hotjar-npm-6.2.0-717faa3339-694ca0c227.zip
  package.json
  src/app/mission/[id]/record/page.tsx
  src/app/mission/[id]/stopwatch/page.tsx
  src/app/mission/new/SelectMissionForm.tsx
  src/app/page.tsx
  src/components/Header/Header.tsx
  src/components/MonitoringInitializer.tsx
  src/utils/event/event.types.ts
  src/utils/event/gtag.ts
  src/utils/event/hotjar.ts
  src/utils/event/index.ts
  src/utils/event/mixpanel.ts
  yarn.lock
Labels: feature

#203 :art: Errorboundary 추가
  public/images/crying-face.png
  src/app/error.tsx
Labels: enhancement

#204 ♻️ Header component 리팩토링
  src/app/auth/nickname/page.tsx
  src/app/guest/mission/new/page.tsx
  src/app/guest/mission/stopwatch/page.tsx
  src/app/mission/[id]/stopwatch/layout.tsx
  src/app/mission/new/CategoryBottomSheet.tsx
  src/app/mission/new/PublicBottomSheet.tsx
  src/app/mission/new/page.tsx
  src/components/BottomSheet/BottomSheet.stories.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Header/Header.stories.tsx
  src/components/Header/Header.tsx
  src/components/Header/Header.types.ts
  src/components/Header/HeaderBase.tsx
  src/components/Header/IconHeader.tsx
  src/components/Header/NoneHeader.tsx
  src/components/Header/TextButtonHeader.tsx
  src/components/Header/index.tsx
Labels: refactor

#208 [Refactor] icon 사이즈 변경 가능하게 수정
  src/components/Icon/AlarmIcon.tsx
  src/components/Icon/ArrowBackIcon.tsx
  src/components/Icon/ArrowDiagonalIcon.tsx
  src/components/Icon/ArrowDownIcon.tsx
  src/components/Icon/ArrowFowardIcon.tsx
  src/components/Icon/CameraIcon.tsx
  src/components/Icon/CheckCircleIcon.tsx
  src/components/Icon/CloseCircleIcon.tsx
  src/components/Icon/CloseIcon.tsx
  src/components/Icon/CopyLinkIcon.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/InputArrowDownIcon.tsx
  src/components/Icon/InputCloseCircleIcon.tsx
  src/components/Icon/MenuIcon.tsx
  src/components/Icon/NavigationHomeIcon.tsx
  src/components/Icon/NavigationMypageIcon.tsx
  src/components/Icon/NavigationResultIcon.tsx
  src/components/Icon/NavigationUsersearchIcon.tsx
  src/components/Icon/NormalClose.tsx
  src/components/Icon/PlusCircleIcon.tsx
  src/components/Icon/PlusCircleLargeIcon.tsx
  src/components/Icon/PlusIcon.tsx
  src/components/Icon/RefreshIcon.tsx
  src/components/Icon/ShareIcon.tsx
  src/components/Icon/TENMMSymbolIcon.tsx
  src/components/Icon/index.tsx
Labels: design

#207 :zap: TextArea컴포넌트 추가
  src/components/TextArea/TextArea.stories.tsx
  src/components/TextArea/TextArea.tsx
Labels: design

#210 🎨 Icon Gallery 스토리 추가
  src/components/Icon/Icon.mdx
  src/components/Icon/index.tsx
Labels: docs, design

#202 🎨 List Component 구현
  .storybook/preview.tsx
  src/components/Button/Button.tsx
  src/components/ListItem/CategoryListItem.tsx
  src/components/ListItem/ListItem.stories.tsx
  src/components/ListItem/ListItem.tsx
  src/components/ListItem/ListItem.types.ts
  src/components/ListItem/MissionListItem.tsx
  src/components/ListItem/ProfileFollowerListItem.tsx
  src/components/ListItem/ProfileListItem.tsx
  src/components/Thumbnail/Thumbnail.tsx
  src/components/Thumbnail/Thumbnail.types.ts
Labels: docs, design

#217 ♻️ Input type='drop-down' Component 생성
  src/app/mission/new/MissionRegistration.tsx
  src/app/mission/new/PublicBottomSheet.tsx
  src/app/mission/new/page.tsx
  src/components/Input/DropdownInput.tsx
  src/components/Input/Input.stories.ts
  src/components/Input/Input.types.ts
  src/constants/mission.ts
Labels: refactor

#212 [Design] snackBar 컴포넌트 추가
  src/app/layout.tsx
  src/components/SnackBar/IconSnackBar.tsx
  src/components/SnackBar/NoneSnackBar.tsx
  src/components/SnackBar/SnackBar.stories.tsx
  src/components/SnackBar/SnackBar.styles.ts
  src/components/SnackBar/SnackBar.tsx
  src/components/SnackBar/SnackBar.types.ts
  src/components/SnackBar/SnackBarOverlay.tsx
  src/components/SnackBar/SnackBarProvider.tsx
  src/components/SnackBar/TextButtonSnackBar.tsx
  src/hooks/mission/stopwatch/useStopwatch.ts
  src/utils/time.ts
Labels: design

#219 ♻️ Input type='normal' 컴포넌트 리팩토링
  src/app/auth/nickname/page.tsx
  src/app/mission/new/MissionRegistration.tsx
  src/components/Input/Input.stories.ts
  src/components/Input/Input.tsx
  src/components/Input/Input.types.ts
  src/components/Input/NormalInput.tsx
Labels: refactor
