Repository depromeet/10mm-client-web, pull requests merged in 2024-01, with the labels that each got.

#234 ✨ 디자인와 다르게 적용되어있던 Input style 수정
  src/app/globals.css
  src/components/Input/Input.stories.ts
  src/components/Input/Input.types.ts
  src/components/Input/NormalInput.tsx
Labels: design

#228 🎨 Mypage Home View 구현
  src/app/mypage/MenuList.tsx
  src/app/mypage/Profile.tsx
  src/app/mypage/VersionInfo.tsx
  src/app/mypage/page.tsx
  src/components/Button/Button.tsx
  src/components/Header/Header.tsx
  src/components/Icon/LogOutIcon.tsx
  src/components/Icon/LoginInInformationIcon.tsx
  src/components/Icon/TermsIcon.tsx
  src/components/Icon/WithdrawalIcon.tsx
  src/components/Icon/index.tsx
  src/constants/router.ts
Labels: design

#230 🎨 닉네임 수정 페이지 View 구현
  src/app/mypage/profile_modify/page.tsx
  src/components/Header/Header.types.ts
  src/components/Header/TextButtonHeader.tsx
  src/components/Input/Input.types.ts
Labels: design

#233 🎨 홈탭 디자인 가이드 수정 적용
  src/app/home/AppBar.tsx
  src/app/home/MissionList.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/BottomDim/BottomDim.tsx
Labels: design

#231 🎨 종료 미션 / 이용약관 / 로그인정보 페이지 / 로그아웃 / 회원탈퇴 View 구현
  src/app/mypage/LogoutDialog.tsx
  src/app/mypage/MenuList.tsx
  src/app/mypage/Profile.tsx
  src/app/mypage/complete_mission/layout.tsx
  src/app/mypage/complete_mission/page.tsx
  src/app/mypage/login_info/layout.tsx
  src/app/mypage/login_info/page.tsx
  src/app/mypage/terms/layout.tsx
  src/app/mypage/terms/page.tsx
  src/app/mypage/withdrawal/layout.tsx
  src/app/mypage/withdrawal/page.tsx
  src/constants/router.ts
Labels: design

#236 [Feat] Tab 컴포넌트 구현
  src/components/Tab/Tab.stories.tsx
  src/components/Tab/Tab.tsx
  src/components/Tab/TabParts.tsx
  src/hooks/useTabs.tsx
Labels: feature

#244 🎨 Thumbnail + appbar bottom 디자인 시스템 수정사항 반영
  src/components/AppBarBottom/AppBarBottom.stories.tsx
  src/components/AppBarBottom/AppBarBottomVIew.tsx
  src/components/Icon/NavigationFeedIcon.tsx
  src/components/Icon/NavigationHomeIcon.tsx
  src/components/Icon/NavigationMissionIcon.tsx
  src/components/Icon/index.tsx
  src/components/ListItem/ListItem.stories.tsx
  src/components/Thumbnail/Thumbnail.tsx
  src/components/Thumbnail/Thumbnail.types.ts
  src/constants/navigation.ts
Labels: design

#256 🎨 badge 새로운 타입 추가
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/Badge.tsx
Labels: docs, design

#257 디자인 시스템 자잘한 수정사항 반영
  src/components/Thumbnail/Thumbnail.tsx
  src/styles/typography.ts
Labels: design

#250 Feat/list item
  src/app/home/MissionList.tsx
  src/app/mypage/complete_mission/page.tsx
  src/components/ListItem/CategoryListItem.tsx
  src/components/ListItem/ListItem.stories.tsx
  src/components/ListItem/ListItem.styles.ts
  src/components/ListItem/ListItem.tsx
  src/components/ListItem/ListItem.types.ts
  src/components/ListItem/MissionListItem.tsx
  src/components/ListItem/OneLineListItem.stories.tsx
  src/components/ListItem/OneLineListItem.tsx
  src/components/ListItem/ProfileFollowerListItem.tsx
  src/components/ListItem/ProfileListItem.stories.tsx
  src/components/ListItem/ProfileListItem.tsx
  src/components/ListItem/TwoLineListItem.stories.tsx
  src/components/ListItem/TwoLineListItem.tsx
  src/components/ListItem/index.tsx
Labels: docs, design

#258 ✨스톱워치 자동 종료 기능 추가
  src/app/mission/[id]/stopwatch/page.tsx
  src/hooks/mission/stopwatch/useStopwatch.ts
Labels: enhancement

#251 [Task] 미션생성 api 연결
  src/apis/index.ts
  src/apis/instance.api.ts
  src/apis/mission.ts
  src/apis/post.ts
  src/app/home/MissionList.tsx
  src/app/mission/new/MissionRegistration.tsx
  src/app/mission/new/useCreateMissionMutation.ts
  src/components/Input/DropdownInput.tsx
  src/components/Input/Input.tsx
  src/components/Input/Input.types.ts
  src/constants/mission.ts
Labels: feature

#260 ✨ 타이머 예외 케이스 대응 > 타이머 상세 페이지
  src/app/mission/[id]/stopwatch/layout.tsx
  src/app/mission/[id]/stopwatch/modals.tsx
  src/app/mission/[id]/stopwatch/page.tsx
Labels: enhancement

#264 🚑️ 미션 인증 페이지 url이 잘됫 되어있던 이슈
  src/app/mission/[id]/stopwatch/page.tsx
  src/constants/router.ts
Labels: hotfix

#268 [Design] bottom sheet animation
  .pnp.cjs
  .yarn/cache/@babel-runtime-npm-7.23.7-9691b86096-b29cf3ca62.zip
  .yarn/cache/@reach-portal-npm-0.13.2-bcac60cdd9-ef6f6d38ce.zip
  .yarn/cache/@reach-utils-npm-0.13.2-a7df0a20f1-606acf46e8.zip
  .yarn/cache/@types-warning-npm-3.0.3-651ad6a5da-862b71c918.zip
  .yarn/cache/@xstate-react-npm-1.6.3-f4e65a4ff8-16a21baca7.zip
  .yarn/cache/body-scroll-lock-npm-3.1.5-fbe946063b-c86f149e5c.zip
  .yarn/cache/focus-trap-npm-6.9.4-64b032bc16-dd64b4522a.zip
  .yarn/cache/react-spring-bottom-sheet-npm-3.4.1-47a91a91b4-760f09a72f.zip
  .yarn/cache/react-spring-npm-8.0.27-e2e99c79a8-e265447b14.zip
  .yarn/cache/react-use-gesture-npm-8.0.1-8d080030e5-229433f49f.zip
  .yarn/cache/tabbable-npm-5.3.3-baf35cffe9-5da150c9ac.zip
  .yarn/cache/use-isomorphic-layout-effect-npm-1.1.2-65facd0a4b-fd3787ed19.zip
  .yarn/cache/use-subscription-npm-1.8.0-b73103d984-beac1f0ff1.zip
  .yarn/cache/use-sync-external-store-npm-1.2.0-44f75d2564-a676216aff.zip
  .yarn/cache/warning-npm-4.0.3-291e921d6d-e7842aff03.zip
  .yarn/cache/xstate-npm-4.38.3-0ca901f715-82f30ed1d0.zip
  package.json
  src/components/BottomSheet/BottomSheet.tsx
  yarn.lock
Labels: design

#261 [Design] menu 컴포넌트
  src/app/mission/[id]/detail/page.tsx
  src/components/Header/Header.stories.tsx
  src/components/Header/Header.tsx
  src/components/Header/Header.types.ts
  src/components/Header/IconHeader.tsx
  src/components/Header/IconMenuHeader.tsx
  src/components/Menu/Menu.contants.ts
  src/components/Menu/Menu.stories.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/Menu.types.ts
  src/components/Menu/MenuContent.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Menu/index.ts
  src/components/Modal/Modal.tsx
  src/hooks/lifeCycle/index.ts
  src/hooks/useDebounce.ts
  src/hooks/useOutsideClick.ts
  src/hooks/useThrottle.ts
Labels: design

#265 ✨ 스톱워치 시간 저장 (주기적 / 웹 이탈 시)
  src/app/mission/[id]/stopwatch/page.tsx
  src/app/mission/[id]/stopwatch/time.hooks.ts
  src/constants/storage.ts
  src/hooks/useInterval.ts
Labels: feature

#272 [Feat] 미션 임시 저장 API 연결
  panda.config.ts
  public/assets/spinner.svg
  src/apis/index.ts
  src/apis/stopwatch.ts
  src/app/mission/[id]/stopwatch/index.hooks.ts
  src/app/mission/[id]/stopwatch/page.tsx
  src/components/Loading/index.tsx
  src/constants/storage.ts
  src/styled-system/tokens/index.css
  src/styled-system/tokens/index.mjs
  src/styled-system/tokens/tokens.d.ts
  src/utils/time.ts
Labels: feature

#275 ✨ 서버 스키마 정의
  src/apis/schema/feed.ts
  src/apis/schema/member.ts
  src/apis/schema/mission.ts
  src/apis/schema/pageable.ts
  src/apis/schema/record.ts
  src/apis/schema/summary.ts
Labels: docs, feature

#278 🚚 record 라우팅 경로 이동
  src/app/mission/[id]/stopwatch/page.tsx
  src/app/record/layout.tsx
  src/app/record/page.tsx
  src/constants/router.ts
Labels: refactor

#279 [Design] TAB style , logic 변경
  src/app/mission/[id]/detail/page.tsx
  src/components/Tab/Tab.hooks.ts
  src/components/Tab/Tab.stories.tsx
  src/components/Tab/Tab.tsx
  src/components/Tab/Tab.types.ts
  src/components/Tab/TabParts.tsx
  src/hooks/useTabs.tsx
Labels: design

#281 🚑️ 라우팅 실수 해결
  src/app/record/[id]/layout.tsx
  src/app/record/[id]/page.tsx
Labels: hotfix

#285 :lipstick: MissionDuration 디자인수정
  src/app/mission/[id]/history/[historyId]/HistoryThumbnail.tsx
  src/app/mission/[id]/history/[historyId]/MissionDuration.tsx
Labels: design

#287 인증화면에서 이탈했을 경우 홈화면 처리
  src/apis/mission.ts
  src/apis/schema/mission.ts
  src/app/home/MissionList.tsx
  src/app/home/home.hooks.ts
  src/components/SnackBar/SnackBar.stories.tsx
Labels: feature

#284 [Task] 미션 단건 조회 api ,미션 내역 조회 api
  panda.config.ts
  src/apis/createQueryKeyFactory.ts
  src/apis/index.ts
  src/apis/instance.api.ts
  src/apis/mission.ts
  src/apis/record.ts
  src/app/home/MissionList.tsx
  src/app/mission/[id]/detail/MissionCalender/MissionCalendar.tsx
  src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistoryBanner.tsx
  src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistoryBannerApi.tsx
  src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistorySkeleton.tsx
  src/app/mission/[id]/detail/MissionHistoryTab.tsx
  src/app/mission/new/MissionRegistration.tsx
  src/constants/mission.ts
  src/styled-system/tokens/index.css
  src/styled-system/tokens/index.mjs
  src/styled-system/tokens/tokens.d.ts
Labels: feature

#291 [Feat] 미션 인증 이미지 업로드 및 API 연결
  src/apis/index.ts
  src/apis/record.ts
  src/apis/schema/record.ts
  src/apis/stopwatch.ts
  src/app/mission/[id]/stopwatch/page.tsx
  src/app/record/[id]/page.tsx
  src/app/record/success/layout.tsx
  src/app/record/success/page.tsx
  src/constants/eventLog.ts
  src/constants/router.ts
  src/hooks/useImage.ts
  src/msw/handlers/record.ts
Labels: feature

#300 [Task] 스낵바 버튼 클릭하면 화면에서 사라지는 기능
  src/components/SnackBar/IconSnackBar.tsx
  src/components/SnackBar/SnackBar.stories.tsx
  src/components/SnackBar/SnackBar.tsx
  src/components/SnackBar/SnackBar.types.ts
  src/components/SnackBar/SnackBarProvider.tsx
  src/components/SnackBar/TextButtonSnackBar.tsx
Labels: design

#299 :sparkles: TextButtonHeaderType 에 rightButtonProps 타입 추가
  src/app/mission/[id]/detail/modify/page.tsx
  src/app/mypage/profile_modify/page.tsx
  src/app/record/detail/[id]/MissionRecordHeader.tsx
  src/app/record/detail/[id]/edit/page.tsx
  src/app/record/detail/empty/page.tsx
  src/components/Header/Header.types.ts
  src/components/Header/TextButtonHeader.tsx
  src/components/Input/DropdownInput.tsx
Labels: enhancement

#305 [Design] 타이머 페이지 디자인 수정사항 반영
  src/app/mission/[id]/stopwatch/page.tsx
  src/hooks/mission/stopwatch/useStopwatchStatus.ts
  src/styled-system/tokens/keyframes.css
  src/styled-system/tokens/tokens.d.ts
  src/styles/motion.ts
Labels: bug fix, design

#306 [Design] 홈탭 디자인 수정사항 반영
  src/app/home/MissionList.tsx
  src/app/home/ProfileList.tsx
Labels: design

#312 [Task] 임시 로그인 구현
  next.config.js
  src/apis/auth.ts
  src/apis/instance.api.ts
  src/app/auth/login/page.tsx
  src/app/auth/nickname/page.tsx
  src/app/auth/signin/page.tsx
  src/app/auth/signup/page.tsx
  src/app/mypage/LogoutDialog.tsx
  src/components/Input/NormalButtonInput.tsx
  src/constants/router.ts
  src/middleware.ts
  src/services/auth/actions.ts
Labels: feature

#309 [Design] banner 컴포넌트 추가
  src/components/Banner/Banner.stories.ts
  src/components/Banner/Banner.tsx
  src/components/Banner/Banner.types.ts
  src/components/Banner/CardBanner.tsx
  src/components/Banner/GraphicBanner.tsx
  src/components/Banner/ListBanner.tsx
Labels: design

#315 [Task] my page 수정 api
  src/apis/auth.ts
  src/apis/member.ts
  src/apis/record.ts
  src/apis/schema/record.ts
  src/apis/schema/upload.ts
  src/app/mypage/Profile.tsx
  src/app/mypage/ProfileContent.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile_modify/page.tsx
  src/components/Thumbnail/NullableThumnail.tsx
  src/hooks/useImage.ts
  src/msw/handlers/index.ts
  src/msw/handlers/member.ts
Labels: feature

#318 [Hotfix] Major issue 핫픽스
  public/assets/mission/10mm-success.svg
  src/apis/auth.ts
  src/apis/instance.api.ts
  src/apis/member.ts
  src/apis/record.ts
  src/apis/schema/mission.ts
  src/app/auth/nickname/page.tsx
  src/app/auth/signin/page.tsx
  src/app/auth/signup/page.tsx
  src/app/guest/mission/stopwatch/page.tsx
  src/app/home/MissionList.tsx
  src/app/home/home.hooks.ts
  src/app/mission/[id]/detail/MissionHistoryTab.tsx
  src/app/mission/[id]/detail/modify/page.tsx
  src/app/mission/[id]/detail/page.tsx
  src/app/mission/[id]/detail/useCheckCompleteMission.tsx
  src/app/mission/[id]/stopwatch/index.hooks.ts
  src/app/mission/[id]/stopwatch/layout.tsx
  src/app/mission/[id]/stopwatch/page.tsx
  src/app/mission/new/MissionRegistration.tsx
  src/app/mission/new/useCreateMissionMutation.ts
  src/app/mypage/LogoutDialog.tsx
  src/app/mypage/Profile.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile_modify/page.tsx
  src/app/mypage/withdrawal/page.tsx
  src/app/page.tsx
  src/app/record/[id]/edit/page.tsx
  src/app/record/[id]/page.tsx
  src/app/record/success/page.tsx
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/Badge.tsx
  src/components/Header/Header.types.ts
  src/components/Header/HeaderBase.tsx
  src/components/Icon/SpinnerIcon.tsx
  src/components/Icon/index.tsx
  src/components/Loading/index.tsx
  src/constants/router.ts
  src/hooks/useAuth.ts
  src/middleware.ts
  src/services/auth/actions.ts
  src/utils/storage/timer.ts
Labels: feature

#321 :bug: event logger id 가 없는 경우 등록하지 않는다
  src/utils/event/gtag.ts
  src/utils/event/hotjar.ts
  src/utils/event/index.ts
  src/utils/event/mixpanel.ts
Labels: bug fix

#322 [Qa] 스타일 수정사항 반영
  src/app/auth/signup/page.tsx
  src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistoryBanner.tsx
  src/components/Input/NormalInput.tsx
  src/constants/mission.ts
Labels: bug fix

#325 ✨ 인증 필요 미션 홈탭에서 체크
  src/apis/mission.ts
  src/apis/schema/mission.ts
  src/app/home/MissionList.tsx
  src/app/home/home.hooks.ts
  src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistoryBannerApi.tsx
Labels: feature

#326 [Feat] 중복 체크기능 구현
  src/apis/member.ts
  src/app/auth/nickname/page.tsx
  src/app/mypage/profile_modify/page.tsx
  src/components/Input/Input.stories.ts
  src/components/Input/Input.types.ts
  src/components/Input/NormalButtonInput.tsx
  src/hooks/useNickname.ts
Labels: feature

#338 [Design] 아이콘 컴포넌트 추가
  src/components/Icon/NormalCalenderIcon.tsx
  src/components/Icon/NormalLinkIcon.tsx
  src/components/Icon/NormalSettingIcon.tsx
  src/components/Icon/NormalTermsIcon.tsx
  src/components/Icon/index.tsx
Labels: design

#333 🎨 Result 페이지 UI 구현
  public/assets/level/1.png
  src/app/globals.css
  src/app/result/LevelStatus/LevelProgressBar.tsx
  src/app/result/LevelStatus/LevelStatus.tsx
  src/app/result/page.tsx
  src/components/AppBarBottom/AppBarBottom.tsx
  src/components/AppBarBottom/AppBarBottomVIew.tsx
  src/components/Banner/CardBanner.tsx
  src/components/Tab/Tab.hooks.ts
  src/components/Tab/Tab.tsx
  src/constants/level.ts
  src/constants/navigation.ts
  src/constants/style.ts
  src/utils/result.ts
Labels: design

#341 [FIX] 미션 생성, 수정
  src/app/home/MissionList.tsx
  src/app/mission/[id]/detail/modify/MissionModify.tsx
  src/app/mission/new/MissionRegistration.tsx
Labels: bug fix

#346 [Task] 홈 UI 변경
  src/apis/member.ts
  src/app/home/AppBar.tsx
  src/app/home/FollowMissionList.tsx
  src/app/home/FollowSummary.tsx
  src/app/home/MissionList.tsx
  src/app/home/ProfileContent.tsx
  src/app/home/ProfileIdProvider.tsx
  src/app/home/ProfileItem.tsx
  src/app/home/ProfileList.tsx
  src/app/home/UserProfile.tsx
  src/app/mypage/ProfileContent.tsx
  src/app/page.tsx
  src/app/result/LevelStatus/LevelProgressBar.tsx
  src/components/Banner/GraphicBanner.tsx
  src/components/Icon/TENMMSymbolCircleIcon.tsx
  src/components/Icon/index.tsx
  src/components/Thumbnail/NullableThumnail.tsx
  src/components/Thumbnail/Thumbnail.tsx
  src/components/Thumbnail/Thumbnail.types.ts
Labels: feature

#348 hotfix: thumbnail image src null 들어가는 이슈 해결
  src/components/Thumbnail/Thumbnail.tsx
  src/components/Thumbnail/Thumbnail.types.ts
Labels: hotfix

#347 [Feat] Level Banner.tsx 추가
  public/assets/level/1.png
  src/apis/instance.api.ts
  src/app/global-error.tsx
  src/app/globals.css
  src/app/home/MissionList.tsx
  src/app/mission/[id]/detail/modify/MissionModify.tsx
  src/app/mission/new/MissionRegistration.tsx
  src/app/mypage/MyProfile.tsx
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/app/result/LevelStatus/LevelProgressBar.tsx
  src/app/result/LevelStatus/LevelStatus.tsx
  src/app/result/page.tsx
  src/components/AppBarBottom/AppBarBottom.tsx
  src/components/AppBarBottom/AppBarBottomVIew.tsx
  src/components/Banner/Banner.tsx
  src/components/Banner/Banner.types.ts
  src/components/Banner/CardBanner.tsx
  src/components/Banner/LevelBanner.tsx
  src/components/Button/Button.tsx
  src/components/Icon/NormalCalenderIcon.tsx
  src/components/Icon/NormalLinkIcon.tsx
  src/components/Icon/NormalSettingIcon.tsx
  src/components/Icon/NormalTermsIcon.tsx
  src/components/Icon/TENMMSymbolCircleIcon.tsx
  src/components/Icon/index.tsx
  src/components/Tab/Tab.hooks.ts
  src/components/Tab/Tab.tsx
  src/constants/level.ts
  src/constants/navigation.ts
  src/constants/style.ts
  src/styled-system/tokens/index.css
  src/styled-system/tokens/index.mjs
  src/styled-system/tokens/tokens.d.ts
  src/styles/color.ts
  src/utils/result.ts
Labels: feature

#294 [Task] page transition
  src/app/layout.tsx
  src/app/template.tsx
  src/components/Layout/index.tsx
  src/constants/common.ts
Labels: feature, design

#352 fix : useSuspense query 대신 useQuery 로 변경
  src/apis/record.ts
  src/app/mission/[id]/detail/MissionCalender/MissionCalendar.tsx
Labels: bug fix

#354 chore : image cdn 도메인 추가
  next.config.js
Labels: enhancement

#335 [Refactor] tanstack query key 관리 방법 변경
  src/apis/createQueryKeyFactory.ts
  src/apis/getQueryKey.ts
  src/apis/member.ts
  src/apis/mission.ts
  src/apis/record.ts
  src/hooks/query/index.ts
Labels: enhancement

#358 [Fix] Typo 수정
  src/app/mypage/profile_modify/page.tsx
Labels: bug fix

#359 배포용 pr
  next.config.js
  src/apis/createQueryKeyFactory.ts
  src/apis/getQueryKey.ts
  src/apis/member.ts
  src/apis/mission.ts
  src/apis/record.ts
  src/app/mypage/ProfileContent.tsx
  src/app/mypage/profile_modify/page.tsx
  src/hooks/query/index.ts
Labels: deploy

#364 [Style] tab css에서 padding 제거
  src/app/mission/[id]/detail/page.tsx
  src/app/result/page.tsx
  src/components/Tab/Tab.tsx
Labels: design

#334 ⚡️ 뒤로가기 동작 수정
  src/app/mission/[id]/detail/MissionHistoryTab.tsx
  src/app/mission/[id]/stopwatch/index.hooks.ts
  src/app/mission/[id]/stopwatch/page.tsx
Labels: bug fix

#373 docs: readme 수정
  README.md
Labels: docs

#377 [Hotfix] mission time storage key 변경
  src/app/guest/mission/stopwatch/page.tsx
  src/app/home/home.hooks.ts
  src/app/mission/[id]/detail/MissionHistoryTab.tsx
  src/app/mission/[id]/stopwatch/index.hooks.ts
  src/app/mission/[id]/stopwatch/page.tsx
  src/constants/storage.ts
  src/hooks/mission/stopwatch/useStopwatch.ts
  src/utils/storage/progressMission.ts
  src/utils/storage/timer.ts
Labels: refactor, hotfix

#381 [Fix] 홈화면 인증필요/진행중 상태 스낵바 기능 수정
  src/app/home/home.hooks.ts
  src/app/mission/[id]/detail/MissionHistoryTab.tsx
  src/app/mission/[id]/detail/page.tsx
  src/components/SnackBar/TextButtonSnackBar.tsx
Labels: enhancement, bug fix

#376 [Feat] CardLevel 컴포넌트 생성
  src/app/home/FollowSummary.tsx
  src/app/level/guide/Character.tsx
  src/app/level/guide/GrowthLevel.tsx
  src/app/level/guide/page.tsx
  src/components/Banner/CardLevel.stories.tsx
  src/components/Banner/CardLevel.tsx
  src/components/Level/LockedCharacter.tsx
  src/components/LevelStatus/LevelStatus.tsx
  src/constants/style/gradient.ts
  src/constants/style/text.ts
Labels: refactor, design

#384 [Task] 팔로우 미션 리스트 api , 팔로우 멤버 리스트 msw 연결
  src/apis/follow.ts
  src/apis/getQueryKey.ts
  src/app/home/FollowMissionList.tsx
  src/app/home/FollowSummary.tsx
  src/app/home/MissionBadge.tsx
  src/app/home/MissionList.tsx
  src/app/home/ProfileContent.tsx
  src/app/home/ProfileIdProvider.tsx
  src/app/home/ProfileItem.tsx
  src/app/home/ProfileList.tsx
  src/app/home/UserProfile.tsx
  src/app/home/home.styles.tsx
  src/app/page.tsx
  src/components/Thumbnail/Thumbnail.tsx
  src/msw/handlers/follow.ts
  src/msw/handlers/index.ts
  src/msw/handlers/member.ts
  src/msw/handlers/mission.ts
Labels: feature

#387 [Hot Feat] Graph 컴포넌트 구현 및 적용
  public/assets/icons/graph/chart.png
  public/assets/icons/graph/clock.png
  src/app/home/FollowSummary.tsx
  src/app/level/guide/page.tsx
  src/app/result/page.tsx
  src/components/Banner/Banner.stories.ts
  src/components/Banner/Banner.types.ts
  src/components/Banner/CardBanner.tsx
  src/components/Banner/CardLevel.tsx
  src/components/Graph/FutureLevelGraph.tsx
  src/components/Graph/Graph.stories.ts
  src/components/Graph/Graph.tsx
  src/components/Graph/Graph.types.ts
  src/components/Graph/GraphBase.tsx
  src/components/Graph/LastLevelGraph.tsx
  src/components/Graph/LevelProgressBar.tsx
  src/components/Graph/PastLevelGraph.tsx
  src/components/Graph/PresentLevelGraph.tsx
  src/components/LevelStatus/LevelStatus.tsx
  src/constants/style/gradient.ts
Labels: feature

#392 [HOFIX] 마이프로필 QA 반영
  src/app/mypage/MenuList.tsx
  src/app/mypage/MyProfile.tsx
  src/app/mypage/page.tsx
  src/app/mypage/profile_modify/page.tsx
  src/app/mypage/setting_and_private/page.tsx
  src/hooks/useImage.ts
Labels: bug fix

#394 style: 0.5px -> 1px
  src/components/Badge/Badge.tsx
  src/components/Banner/CardBanner.tsx
  src/constants/style/gradient.ts
  src/styled-system/tokens/index.css
  src/styled-system/tokens/index.mjs
  src/styled-system/tokens/tokens.d.ts
  src/styles/color.ts
Labels: hotfix, style

#399 [Fix] 중복확인 버튼 위치 수정
  src/components/Input/NormalButtonInput.tsx
Labels: bug fix

#405 chore: 웹뷰 핀치줌 막기
  src/app/layout.tsx
Labels: bug fix, design

#403 chore: 아이디 로그인 제거
  src/app/auth/login/page.tsx
Labels: design

#402 chore: 웹 애니메이션 임시 제거
  src/app/template.tsx
Labels: bug fix

#407 chore: 놓친 메타태그 추가
  src/app/layout.tsx
Labels: bug fix, hotfix, 리뷰필요함

#410 Bug/remove web routing
  src/app/layout.tsx
Labels: 리뷰필요함

#414 폰트 적용방식 변경
  src/app/globals.css
  src/app/layout.tsx
  src/assets/fonts/PretendardVariable.woff2
  src/styles/font.ts
Labels: 리뷰필요함

#413 chore:css웹뷰세팅 추가
  src/app/globals.css
Labels: bug fix, design

#396 [Feat] 닉네임 검색 페이지 구현
  src/apis/follow.ts
  src/apis/getQueryKey.ts
  src/apis/member.ts
  src/apis/schema/member.ts
  src/app/home/AppBar.tsx
  src/app/search/layout.tsx
  src/app/search/page.tsx
  src/components/Icon/NavigationSearchIcon.tsx
  src/components/Icon/index.tsx
  src/components/ListItem/Follow/FollowerItem.tsx
  src/components/ListItem/Follow/FollowingItem.tsx
  src/components/ListItem/ProfileListItem.stories.tsx
  src/components/ListItem/ProfileListItem.tsx
  src/components/SearchBar/SearchBar.tsx
  src/constants/router.ts
Labels: feature

#397 [Task] 타인 프로필 UI 구현
  src/apis/follow.ts
  src/apis/getQueryKey.ts
  src/apis/member.ts
  src/app/home/FollowContent.tsx
  src/app/home/FollowList.tsx
  src/app/home/FollowMissionList.tsx
  src/app/home/FollowSummary.tsx
  src/app/home/ProfileItem.tsx
  src/app/home/UserProfile.tsx
  src/app/mypage/MyProfile.tsx
  src/app/mypage/MyProfileMissionList.tsx
  src/app/page.tsx
  src/app/profile/[id]/FollowButton.tsx
  src/app/profile/[id]/ProfileContent.tsx
  src/app/profile/[id]/page.tsx
  src/components/Button/GradientTextButton.tsx
  src/components/Thumbnail/Thumbnail.types.ts
  src/constants/router.ts
  src/utils/result.ts
Labels: feature

#421 fix : 이미지의 확장자를 서버에서 받아온 데이터로 보내준다
  src/apis/member.ts
  src/apis/schema/member.ts
  src/app/mypage/profile_modify/page.tsx
  src/hooks/useImage.ts
Labels: enhancement

#420 [Task] 팔로우(친구) 미션 상세페이지
  src/apis/record.ts
  src/app/home/FollowMissionList.tsx
  src/app/mission/[id]/detail/MissionCalender/MissionCalendar.tsx
  src/app/mission/[id]/detail/MissionCalender/MissionCalendar.utils.ts
  src/app/mission/[id]/detail/MissionCalender/MissionCalendarItem.tsx
  src/app/mission/[id]/detail/MissionHistoryTab.tsx
  src/app/mission/[id]/detail/MissionStartButton.tsx
  src/app/mission/[id]/detail/page.tsx
  src/app/mission/[id]/follow/page.tsx
  src/app/record/[id]/follow/page.tsx
  src/constants/router.ts
Labels: feature, design

#423 배포용 PR
  src/apis/follow.ts
  src/apis/getQueryKey.ts
  src/apis/member.ts
  src/apis/mission.ts
  src/apis/record.ts
  src/apis/schema/member.ts
  src/app/guest/mission/stopwatch/page.tsx
  src/app/home/AppBar.tsx
  src/app/home/FollowContent.tsx
  src/app/home/FollowList.tsx
  src/app/home/FollowMissionList.tsx
  src/app/home/FollowSummary.tsx
  src/app/home/MissionBadge.tsx
  src/app/home/MissionInnerList.tsx
  src/app/home/MissionList.tsx
  src/app/home/ProfileIdProvider.tsx
  src/app/home/ProfileItem.tsx
  src/app/home/ProfileList.tsx
  src/app/home/UserProfile.tsx
  src/app/home/home.styles.tsx
  src/app/mission/[id]/detail/MissionCalender/MissionCalendar.tsx
  src/app/mission/[id]/detail/MissionCalender/MissionCalendar.utils.ts
  src/app/mission/[id]/detail/MissionCalender/MissionCalendarItem.tsx
  src/app/mission/[id]/detail/MissionHistoryTab.tsx
  src/app/mission/[id]/detail/MissionStartButton.tsx
  src/app/mission/[id]/detail/page.tsx
  src/app/mission/[id]/follow/page.tsx
  src/app/mission/[id]/stopwatch/page.tsx
  src/app/mypage/MyProfile.tsx
  src/app/mypage/MyProfileMissionList.tsx
  src/app/mypage/profile_modify/page.tsx
  src/app/page.tsx
  src/app/profile/[id]/FollowButton.tsx
  src/app/profile/[id]/ProfileContent.tsx
  src/app/profile/[id]/page.tsx
  src/app/record/[id]/follow/page.tsx
  src/app/search/layout.tsx
  src/app/search/page.tsx
  src/components/Button/GradientTextButton.tsx
  src/components/Icon/NavigationSearchIcon.tsx
  src/components/Icon/index.tsx
  src/components/ListItem/Follow/FollowerItem.tsx
  src/components/ListItem/Follow/FollowingItem.tsx
  src/components/ListItem/ProfileListItem.stories.tsx
  src/components/ListItem/ProfileListItem.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/Stopwatch/Stopwatch.stories.tsx
  src/components/Stopwatch/Stopwatch.tsx
  src/components/Thumbnail/Thumbnail.tsx
  src/components/Thumbnail/Thumbnail.types.ts
  src/constants/router.ts
  src/hooks/useImage.ts
  src/msw/handlers/follow.ts
  src/msw/handlers/index.ts
  src/msw/handlers/member.ts
  src/msw/handlers/mission.ts
  src/utils/result.ts
Labels: feature

#431 [Hotfix] 스톱워치 페이지에서 그라데이션이 잘리는 문제 수정
  src/app/guest/mission/stopwatch/page.tsx
  src/app/mission/[id]/stopwatch/page.tsx
  src/app/profile/[id]/ProfileContent.tsx
  src/components/Banner/Banner.stories.tsx
  src/components/Banner/Banner.tsx
  src/components/Banner/Banner.types.ts
  src/components/Banner/CardBanner.tsx
  src/components/Banner/GraphicBanner.tsx
  src/components/Banner/ListBanner.tsx
  src/components/Banner/ListLevelBanner.tsx
  src/components/Stopwatch/Stopwatch.tsx
  src/components/Stopwatch/StopwatchContainer.tsx
Labels: bug fix, design

#435 Design/button cta medium
  src/app/auth/nickname/page.tsx
  src/app/guest/mission/new/page.tsx
  src/app/mission/[id]/detail/MissionStartButton.tsx
  src/app/mission/new/MissionRegistration.tsx
  src/components/Button/Button.tsx
Labels: bug fix, style

#434 [Fix] 마이페이지 UI 변경사항 적용
  src/app/auth/nickname/page.tsx
  src/app/guest/mission/new/page.tsx
  src/app/level/guide/page.tsx
  src/app/mission/[id]/detail/MissionStartButton.tsx
  src/app/mission/new/MissionRegistration.tsx
  src/app/mypage/profile_modify/page.tsx
  src/components/Button/Button.tsx
  src/components/Graph/FutureLevelGraph.tsx
Labels: bug fix

#439 제니퍼 프론트 모니터링 툴 추가
  src/components/MonitoringInitializer.tsx
Labels: enhancement

#442 [Fix] QA 수정사항 반영 및 디자인 시스템 수정사항 반영
  src/apis/follow.ts
  src/apis/record.ts
  src/apis/schema/member.ts
  src/app/guest/mission/stopwatch/page.tsx
  src/app/home/FollowContent.tsx
  src/app/home/FollowSummary.tsx
  src/app/mission/[id]/detail/MissionCalender/MissionCalendar.tsx
  src/app/mission/[id]/detail/MissionCalender/MissionCalendar.utils.ts
  src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistoryBannerApi.tsx
  src/app/mission/[id]/detail/MissionHistoryTab.tsx
  src/app/mission/[id]/stopwatch/page.tsx
  src/app/record/[id]/detail/HistoryThumbnail.tsx
  src/app/record/[id]/page.tsx
  src/app/search/page.tsx
  src/components/AppBarBottom/AppBarBottomVIew.tsx
  src/components/Header/Header.stories.tsx
  src/components/Header/Header.tsx
  src/components/Header/Header.types.ts
  src/components/Header/HeaderBase.tsx
  src/components/Header/IconHeader.tsx
  src/components/Header/IconMenuHeader.tsx
  src/components/Header/RightComponentHeader.tsx
  src/components/ListItem/TwoLineListItem.tsx
  src/components/Stopwatch/StopwatchContainer.tsx
  src/components/Thumbnail/Thumbnail.tsx
  src/components/Thumbnail/Thumbnail.types.ts
Labels: bug fix, design

#444 [Fix] 미션캘린더 뷰에서 오늘 이후의 날짜는 라우팅 되지 않는다
  src/app/mission/[id]/detail/MissionCalender/MissionCalendar.utils.ts
Labels: enhancement
