Repository depromeet/10mm-client-web, pull requests merged in 2024-03, with the labels that each got.

#614 일지 줄바꿈 처리
  src/app/record/[id]/detail/MissionRecordDetail.tsx
Labels: enhancement

#611 [Test] ProgressMission util Test
  src/hooks/mission/stopwatch/useStopwatch.ts
  src/utils/storage/progressMission.test.ts
  src/utils/storage/progressMission.ts
Labels: test

#612 [Test] Progress Mission Data Get Logic Test
  src/utils/storage/progressMission.test.ts
Labels: test

#617 Feed에 페이지네이션 적용
  src/apis/feed.ts
  src/apis/getQueryKey.ts
  src/app/feed/FeedList.tsx
  src/app/feed/FeedSection.tsx
  src/hooks/useIntersect.ts
  src/styles/position.ts
Labels: feature

#618 배포용 PR
  src/apis/feed.ts
  src/apis/getQueryKey.ts
  src/app/feed/FeedList.tsx
  src/app/feed/FeedSection.tsx
  src/app/record/[id]/detail/MissionRecordDetail.tsx
  src/hooks/mission/stopwatch/useStopwatch.ts
  src/hooks/useIntersect.ts
  src/styles/position.ts
  src/utils/storage/progressMission.test.ts
  src/utils/storage/progressMission.ts
Labels: deploy

#619 배포용 PR
  src/apis/feed.ts
  src/apis/getQueryKey.ts
  src/app/feed/FeedList.tsx
  src/app/feed/FeedSection.tsx
  src/app/record/[id]/detail/MissionRecordDetail.tsx
  src/hooks/mission/stopwatch/useStopwatch.ts
  src/hooks/useIntersect.ts
  src/styles/position.ts
  src/utils/storage/progressMission.test.ts
  src/utils/storage/progressMission.ts
Labels: deploy

#615 스톱워치 페이지 리팩토링
  src/app/guest/mission/stopwatch/page.tsx
  src/app/mission/[id]/stopwatch/ButtonSection.tsx
  src/app/mission/[id]/stopwatch/Header.tsx
  src/app/mission/[id]/stopwatch/Modal.context.tsx
  src/app/mission/[id]/stopwatch/Stopwatch.context.tsx
  src/app/mission/[id]/stopwatch/StopwatchSection.tsx
  src/app/mission/[id]/stopwatch/TextSection.tsx
  src/app/mission/[id]/stopwatch/index.hooks.ts
  src/app/mission/[id]/stopwatch/modals.tsx
  src/app/mission/[id]/stopwatch/page.tsx
  src/hooks/mission/stopwatch/useStopwatch.ts
  src/hooks/mission/stopwatch/useStopwatchLogic.ts
  src/hooks/mission/stopwatch/useStopwatchStatus.ts
  src/hooks/useModal.tsx
  src/utils/storage/progressMission.ts
Labels: refactor

#622 숨겨진 다락방 이슈 해결
  src/app/record/[id]/detail/MissionRecordDetail.tsx
Labels: style

#621 10분뒤에 인증 가능 알림
  src/apis/notifications.ts
  src/app/mission/[id]/stopwatch/ButtonSection.tsx
Labels: feature

#623 피드 일지에 줄바꿈 적용
  src/app/feed/FeedItem.tsx
Labels: hotfix

#624 배포용 PR
  src/apis/notifications.ts
  src/app/feed/FeedItem.tsx
  src/app/guest/mission/stopwatch/page.tsx
  src/app/mission/[id]/stopwatch/ButtonSection.tsx
  src/app/mission/[id]/stopwatch/Header.tsx
  src/app/mission/[id]/stopwatch/Modal.context.tsx
  src/app/mission/[id]/stopwatch/Stopwatch.context.tsx
  src/app/mission/[id]/stopwatch/StopwatchSection.tsx
  src/app/mission/[id]/stopwatch/TextSection.tsx
  src/app/mission/[id]/stopwatch/index.hooks.ts
  src/app/mission/[id]/stopwatch/modals.tsx
  src/app/mission/[id]/stopwatch/page.tsx
  src/app/record/[id]/detail/MissionRecordDetail.tsx
  src/hooks/mission/stopwatch/useStopwatch.ts
  src/hooks/mission/stopwatch/useStopwatchLogic.ts
  src/hooks/mission/stopwatch/useStopwatchStatus.ts
  src/hooks/useModal.tsx
  src/utils/storage/progressMission.ts
Labels: feature

#626 [Page Router] pageExtensions 적용
  next.config.js
  src/pages/_app.page.tsx
  src/pages/_document.page.tsx
  src/pages/auth/kakaoCallback/index.page.tsx
  src/pages/auth/login/index.page.tsx
  src/pages/auth/nickname/index.page.tsx
  src/pages/auth/signin/index.page.tsx
  src/pages/auth/signup/index.page.tsx
  src/pages/index.page.tsx
Labels: refactor, hotfix

#629 [Page Router] Feed Flow
  src/app/mypage/FeedThumbnail.tsx
  src/app/record/[id]/detail/layout.tsx
  src/app/record/[id]/follow/page.tsx
  src/components/Header/Header.tsx
  src/components/MissionDuration.tsx
  src/components/Tab/Tab.tsx
  src/pages/feed/FeedItem.tsx
  src/pages/feed/FeedList.tsx
  src/pages/feed/FeedSection.tsx
  src/pages/feed/HistoryThumbnail.tsx
  src/pages/feed/index.page.tsx
  src/pages/home/AppBar.tsx
  src/pages/record/[id]/detail/MissionRecordDetail.tsx
  src/pages/record/[id]/detail/MissionRecordHeader.tsx
  src/pages/record/[id]/detail/index.page.tsx
  src/pages/record/[id]/follow.page.tsx
Labels: refactor

#631 [Page Router] Mypage Flow
  src/app/mypage/Profile.tsx
  src/app/mypage/ProfileContent.tsx
  src/app/mypage/VersionInfo.tsx
  src/app/mypage/complete_mission/layout.tsx
  src/app/mypage/complete_mission/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/login_info/layout.tsx
  src/app/mypage/setting_and_private/layout.tsx
  src/app/mypage/setting_and_private/page.tsx
  src/app/mypage/terms/layout.tsx
  src/app/mypage/terms/page.tsx
  src/app/mypage/withdrawal/layout.tsx
  src/app/mypage/withdrawal/page.tsx
  src/app/profile/[id]/page.tsx
  src/components/ProfileContent.tsx
  src/components/ProfileTab/FeedThumbnail.tsx
  src/components/ProfileTab/FollowMissionList.tsx
  src/components/ProfileTab/MissionInnerList.tsx
  src/components/ProfileTab/ProfileFeedItem.tsx
  src/components/ProfileTab/ProfileFeedList.tsx
  src/components/ProfileTab/ProfileMissionList.tsx
  src/components/ProfileTab/ProfileTab.tsx
  src/constants/router.ts
  src/pages/mypage/Header.tsx
  src/pages/mypage/MyProfile.tsx
  src/pages/mypage/index.page.tsx
  src/pages/mypage/login_info/index.page.tsx
  src/pages/mypage/profile_modify.page.tsx
  src/pages/mypage/setting_and_private/LogoutDialog.tsx
  src/pages/mypage/setting_and_private/MenuList.tsx
  src/pages/mypage/setting_and_private/index.page.tsx
  src/pages/mypage/terms/index.page.tsx
  src/pages/mypage/terms/terms.constants.ts
  src/pages/mypage/withdrawal/index.page.tsx
Labels: refactor

#635 [Page Router] search 페이지
  src/app/search/layout.tsx
  src/components/SearchBar/SearchBar.tsx
  src/pages/search/index.page.tsx
Labels: refactor

#636 fix : profile/[id] page router 변경
  src/app/auth/kakaoCallback/page.tsx
  src/app/auth/login/layout.tsx
  src/app/auth/login/page.tsx
  src/app/auth/nickname/page.tsx
  src/app/auth/signin/page.tsx
  src/app/auth/signup/page.tsx
  src/pages/profile/[id]/FollowButton.tsx
  src/pages/profile/[id]/index.page.tsx
Labels: refactor

#639 fix: 오늘 시작 미션이 아니여도 삭제하지 않음
  src/utils/storage/progressMission.test.ts
  src/utils/storage/progressMission.ts
Labels: feature, bug fix

#641 chip component 추가 및 스토리북 적용
  src/components/Chip/Chip.stories.ts
  src/components/Chip/Chip.tsx
Labels: design

#640 디자인 시스템 fix 건들 한번에 반영
  src/app/mission/new/MissionRegistration.tsx
  src/app/mission/new/page.tsx
  src/components/Input/DropdownInput.tsx
  src/components/Input/NormalButtonInput.tsx
  src/components/Input/NormalInput.tsx
Labels: design

#642 [TMN-58] 회원가입 후 온보딩
  public/assets/character/basic.png
  public/assets/character/flag.png
  public/assets/character/sad.png
  src/apis/auth.ts
  src/app/auth/kakaoCallback/page.tsx
  src/app/auth/login/page.tsx
  src/app/onboarding/RecommendFollowItem.tsx
  src/app/onboarding/onboarding.constants.ts
  src/app/onboarding/page.tsx
  src/components/Header/CenterTextHeader.tsx
  src/constants/eventLog.ts
  src/constants/router.ts
  src/utils/appEnv.ts
Labels: feature
