Repository depromeet/10mm-client-web, pull requests merged in 2024-02, with the labels that each got.

#447 [Design] snackbar 컬러변경
  src/components/SnackBar/SnackBar.styles.ts
Labels: design

#450 [Feat] 백그라운드에서도 타이머가 돌아갈 수 있도록
  src/app/mission/[id]/stopwatch/page.tsx
  src/constants/storage.ts
  src/hooks/mission/stopwatch/useStopwatch.ts
  src/utils/storage/progressMission.ts
Labels: feature, bug fix

#451 배포용 PR
  src/app/mission/[id]/stopwatch/page.tsx
  src/components/SnackBar/SnackBar.styles.ts
  src/constants/storage.ts
  src/hooks/mission/stopwatch/useStopwatch.ts
  src/utils/storage/progressMission.ts
Labels: deploy

#455 [FIX] 닉네임이 공백으로 수정 가능한 이슈
  src/hooks/useNickname.ts
Labels: bug fix

#456 :bug: 안드로이드 앱 카카오 로그인 버그 수정
  src/app/auth/login/page.tsx
Labels: bug fix

#466 feat: full tab component 생성
  src/components/Tab/FullTab.tsx
  src/components/Tab/FullTabParts.tsx
  src/components/Tab/Tab.stories.tsx
  src/components/Tab/Tab.types.ts
Labels: design

#469 [FEAT] 이전 달의 미션 캘린더 정보를 볼 수 있다.
  src/app/mission/[id]/detail/MissionCalender/MissionCalendar.tsx
  src/app/mission/[id]/detail/MissionCalender/MissionCalendar.utils.ts
  src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistoryBannerApi.tsx
  src/app/mission/[id]/detail/MissionHistoryTab.tsx
  src/hooks/useCalendar.ts
  src/hooks/useSearchParamState.ts
Labels: feature

#448 feat: 로그인시 디바이스 토큰 업데이트
  src/apis/auth.ts
  src/app/auth/login/page.tsx
Labels: feature

#474 [Hofix] 서버에서 401 error가 뜨면 로그인 페이지로 라우팅합니다.
  src/apis/instance.api.ts
  src/app/error.tsx
  src/app/template.tsx
  src/hooks/useAuth.ts
  src/utils/appEnv.ts
Labels: bug fix

#479 [FIX] 로그인 cookie
  src/apis/instance.api.ts
Labels: bug fix

#480 [Revert] "Merge pull request #479 from depromeet/hofix/401-error"
  src/apis/instance.api.ts
Labels: bug fix

#486 배포용 PR
  src/apis/follow.ts
  src/apis/getQueryKey.ts
  src/apis/member.ts
  src/apis/schema/member.ts
  src/app/mypage/MyProfile.tsx
  src/app/profile/[id]/FollowButton.tsx
  src/app/profile/[id]/ProfileContent.tsx
  src/app/profile/[id]/follows/FollowingList.tsx
  src/app/profile/[id]/follows/MyFollowerList.tsx
  src/app/profile/[id]/follows/index.hooks.ts
  src/app/profile/[id]/follows/index.utils.ts
  src/app/profile/[id]/follows/page.tsx
  src/app/profile/[id]/page.tsx
  src/app/search/page.tsx
  src/components/Header/Header.types.ts
  src/components/Header/HeaderBase.tsx
  src/components/ListItem/Follow/FollowerItem.tsx
  src/components/ListItem/Follow/FollowingItem.tsx
  src/components/ListItem/Follow/MemberItem.tsx
  src/components/ListItem/ProfileListItem.tsx
  src/components/Motion/Motion.constants.ts
  src/components/Motion/StaggerWrapper.tsx
  src/components/Tab/FullTabParts.tsx
  src/components/Tab/Tab.hooks.ts
  src/components/Tab/Tab.types.ts
  src/constants/router.ts
Labels: deploy

#487 배포용 PR
  src/app/profile/[id]/follows/FollowingList.tsx
  src/app/profile/[id]/follows/MyFollowerList.tsx
  src/app/search/page.tsx
Labels: design, deploy

#488 [Feat] 10분 기록시 체크 이벤트 등록
  src/constants/eventLog.ts
  src/hooks/mission/stopwatch/useStopwatch.ts
  src/utils/storage/progressMission.ts
Labels: feature

#489 [Fix] 여러가지 수정사항 반영
  src/app/home/FollowList.tsx
  src/app/home/FollowMissionList.tsx
  src/app/home/FollowSummary.tsx
  src/app/home/MissionInnerList.tsx
  src/app/home/ProfileItem.tsx
  src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistoryBanner.tsx
  src/app/mission/[id]/follow/page.tsx
  src/app/mypage/MyProfile.tsx
  src/app/profile/[id]/FollowButton.tsx
  src/app/profile/[id]/ProfileContent.tsx
  src/app/profile/[id]/follows/FollowingList.tsx
  src/app/profile/[id]/follows/page.tsx
  src/app/record/[id]/page.tsx
  src/app/record/success/layout.tsx
  src/app/search/page.tsx
  src/components/BottomDim/BottomDim.tsx
  src/components/Button/GradientTextButton.tsx
  src/components/Graph/LevelProgressBar.tsx
  src/components/ListItem/Follow/MemberItem.tsx
  src/components/Motion/StaggerWrapper.tsx
  src/components/SearchBar/SearchBar.tsx
  src/components/SnackBar/SnackBar.types.ts
  src/components/SnackBar/SnackBarOverlay.tsx
  src/hooks/query/useMutationHandleError.ts
Labels: enhancement, bug fix, design

#485 [FEAT] feed tab 구현
  src/apis/feed.ts
  src/apis/getQueryKey.ts
  src/app/feed/FeedItem.tsx
  src/app/feed/FeedList.tsx
  src/app/feed/page.tsx
  src/components/ListItem/ProfileListItem.tsx
  src/constants/navigation.ts
  src/constants/router.ts
  src/msw/handlers/feed.ts
  src/msw/handlers/follow.ts
  src/msw/handlers/index.ts
Labels: feature

#505 [Fix] Button Blocked 추가 & 프로필 팔로우/팔로잉 버튼 API 중복 호출 수정
  src/app/profile/[id]/FollowButton.tsx
  src/app/profile/[id]/page.tsx
  src/components/Button/Button.tsx
  src/components/Button/GradientTextButton.tsx
  src/components/ListItem/Follow/MemberItem.tsx
Labels: refactor, bug fix

#513 [FIX] 미션 수정 페이지 리프레시 오류 fix
  src/apis/instance.api.ts
  src/app/layout.tsx
Labels: bug fix

#508 [Fix] 인증 실패 메시지 뜨는 문제 수정
  src/app/record/[id]/page.tsx
Labels: bug fix

#521 [Design] 홈에서 뜨는 미션 리스트들 그냥 기존처럼 애니메이션 없이 바로 뜨는 방향으로 수정
  src/app/home/FollowMissionList.tsx
  src/app/home/MissionInnerList.tsx
Labels: design

#525 [Feat] 홈화면 피드백 반영
  src/app/home/FollowList.tsx
  src/app/home/MissionList.tsx
Labels: feature, design

#532 [Fix] 잠금의 경우에도 현재 레벨이라는 텍스트가 보이는 부분을 수정
  src/app/level/guide/page.tsx
  src/components/Banner/CardBanner.tsx
Labels: bug fix

#531 [Style] card banner border fix!
  src/components/Banner/CardBanner.tsx
Labels: bug fix, design

#519 [Feat] 재촉하기 기능
  src/apis/notifications.ts
  src/apis/record.ts
  src/app/mission/[id]/follow/page.tsx
  src/components/MissionDetail/MissionCalender/MissionCalendar.tsx
  src/components/MissionDetail/MissionCalender/UrgingButton/GradientPaperAirplaneIcon.tsx
  src/components/MissionDetail/MissionCalender/UrgingButton/UrgingButton.tsx
Labels: feature, design

#548 배포용 PR
  src/apis/notifications.ts
  src/apis/record.ts
  src/app/mission/[id]/follow/page.tsx
  src/components/Header/HeaderBase.tsx
  src/components/MissionDetail/MissionCalender/MissionCalendar.tsx
  src/components/MissionDetail/MissionCalender/UrgingButton/GradientPaperAirplaneIcon.tsx
  src/components/MissionDetail/MissionCalender/UrgingButton/UrgingButton.tsx
Labels: deploy

#530 [Feat] 현황 full 기능 구현
  public/assets/result/character-bg-gradient.svg
  src/apis/getQueryKey.ts
  src/apis/result.ts
  src/app/home/FollowList.tsx
  src/app/home/ProfileItem.tsx
  src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistorySkeleton.tsx
  src/app/result/OverallStatus.tsx
  src/app/result/OverallStatus/BannerSection.tsx
  src/app/result/OverallStatus/Calendar.tsx
  src/app/result/OverallStatus/CalendarItem.tsx
  src/app/result/OverallStatus/ImageAreaSection.tsx
  src/app/result/OverallStatus/MissionList.tsx
  src/app/result/OverallStatus/MissionSection.tsx
  src/app/result/OverallStatus/index.tsx
  src/app/result/layout.tsx
  src/app/result/page.tsx
  src/components/Banner/CardBanner.tsx
  src/components/Graph/GraphBase.tsx
  src/components/Icon/NormalCalenderIcon.tsx
  src/components/Icon/SymbolFillIcon.tsx
  src/components/Icon/index.tsx
  src/components/ListItem/OneLineListItem.tsx
  src/components/ListItem/ProfileListItem.tsx
  src/components/ListItem/TwoLineListItem.tsx
  src/components/ProgressBar.tsx
  src/constants/eventLog.ts
  src/constants/router.ts
  src/constants/style/text.ts
  src/msw/handlers/result.ts
  src/utils/result.ts
Labels: feature, style

#550 배포용 PR
  public/images/reaction/BLUE_HEART.png
  public/images/reaction/EYES.png
  public/images/reaction/FIRE.png
  public/images/reaction/GLOWING_STAR.png
  public/images/reaction/PARTYING_FACE.png
  public/images/reaction/PARTY_POPPER.png
  public/images/reaction/PURPLE_HEART.png
  public/images/reaction/SOMETHING_SPECIAL.png
  public/images/reaction/SPARKLING_HEART.png
  public/images/reaction/THUMBS_UP.png
  public/images/reaction/UNICORN.png
  src/apis/getQueryKey.ts
  src/apis/member.ts
  src/apis/reaction.ts
  src/apis/schema/reaction.ts
  src/app/feed/FeedItem.tsx
  src/app/record/[id]/detail/MissionRecordDetail.tsx
  src/app/record/[id]/detail/page.tsx
  src/app/record/[id]/follow/page.tsx
  src/app/result/page.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Icon/NavigationFeedIcon.tsx
  src/components/Icon/index.tsx
  src/components/ReactionBar/MyReactionBar/MyReactionBar.tsx
  src/components/ReactionBar/OtherReactionBar/OtherReactionBar.tsx
  src/components/ReactionBar/ReactionBar.style.ts
  src/components/ReactionBar/ReactionBar.tsx
  src/components/ReactionBar/ReactionBottomSheet.tsx
  src/components/ReactionBar/ReactionList.tsx
  src/constants/eventLog.ts
  src/constants/style/scroll.ts
Labels: deploy

#567 fix : 확인 버튼 zIndex 수정
  src/app/guest/mission/success/page.tsx
  src/app/record/success/page.tsx
Labels: bug fix

#571 [Fix] QA 수정사항 반영
  src/apis/result.ts
  src/app/home/FollowContent.tsx
  src/app/home/FollowMissionList.tsx
  src/app/home/FollowSummary.tsx
  src/app/home/home.styles.tsx
  src/app/level/guide/Character.tsx
  src/app/level/guide/page.tsx
  src/app/mission/new/CategoryBottomSheet.tsx
  src/app/mypage/ProfileTab.tsx
  src/app/profile/[id]/ProfileContent.tsx
  src/app/profile/[id]/follows/index.utils.ts
  src/app/profile/[id]/page.tsx
  src/app/result/FinishedMissionList.tsx
  src/app/result/OverallStatus/Calendar.tsx
  src/app/result/OverallStatus/MissionList.tsx
  src/app/result/OverallStatus/MissionSection.tsx
  src/app/result/OverallStatus/index.tsx
  src/components/Banner/CardBanner.tsx
  src/components/Banner/GraphicBanner.tsx
  src/components/Banner/ListLevelBanner.tsx
  src/components/Empty/Empty.tsx
  src/components/Input/DropdownInput.tsx
  src/components/ReactionBar/OtherReactionBar/OtherReactionBar.tsx
  src/components/ReactionBar/ReactionBottomSheet.tsx
Labels: bug fix

#573 배포용 PR
  src/components/BottomSheet/BottomSheet.tsx
  src/utils/storage/progressMission.ts
Labels: deploy

#581 [Feat] 전체 피드 기능 추가
  src/apis/feed.ts
  src/apis/getQueryKey.ts
  src/app/feed/FeedItem.tsx
  src/app/feed/FeedList.tsx
  src/app/feed/FeedSection.tsx
  src/app/feed/page.tsx
  src/hooks/useShowGuide.ts
Labels: enhancement

#583 배포용 PR
  src/apis/feed.ts
  src/apis/getQueryKey.ts
  src/app/feed/FeedItem.tsx
  src/app/feed/FeedList.tsx
  src/app/feed/FeedSection.tsx
  src/app/feed/page.tsx
  src/hooks/useShowGuide.ts
Labels: deploy

#585 [Feat] Reaction 추가기능 반영
  src/apis/reaction.ts
  src/apis/schema/feed.ts
  src/app/feed/FeedItem.tsx
  src/app/home/FollowContent/FollowMissionList.tsx
  src/app/home/FollowContent/MyMissionInnerList.tsx
  src/app/home/FollowContent/MyMissionList.tsx
  src/app/home/FollowContent/index.tsx
  src/components/AppBarBottom/AppBarBottomVIew.tsx
  src/components/Icon/TrashcanIcon.tsx
  src/components/Icon/index.tsx
  src/components/ListItem/TwoLineListItem.tsx
  src/components/MissionList/ReactionLinkItem.tsx
  src/components/MissionList/index.tsx
  src/components/ReactionBar/MyReactionBar/MyReactionBar.tsx
  src/components/ReactionBar/OtherReactionBar/OtherReactionBar.tsx
  src/components/ReactionBar/ReactionBottomSheet.tsx
  src/components/SnackBar/SnackBarOverlay.tsx
  src/constants/eventLog.ts
Labels: enhancement, bug fix

#590 배포용 PR
  src/apis/reaction.ts
  src/apis/schema/feed.ts
  src/app/feed/FeedItem.tsx
  src/app/home/FollowContent/FollowMissionList.tsx
  src/app/home/FollowContent/FollowSummary.tsx
  src/app/home/FollowContent/MyMissionInnerList.tsx
  src/app/home/FollowContent/MyMissionList.tsx
  src/app/home/FollowContent/index.tsx
  src/app/home/FollowList/ProfileItem.tsx
  src/app/home/FollowList/UserProfile.tsx
  src/app/home/FollowList/index.tsx
  src/app/home/MissionInnerList.tsx
  src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistoryBanner.tsx
  src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistoryBannerApi.tsx
  src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistorySkeleton.tsx
  src/app/mission/[id]/detail/MissionStatistics.tsx
  src/app/mission/[id]/follow/page.tsx
  src/app/mypage/MyProfile.tsx
  src/app/mypage/ProfileMissionList.tsx
  src/app/mypage/refactor/FollowMissionList.tsx
  src/app/mypage/refactor/MissionInnerList.tsx
  src/app/result/OverallStatus/MissionList.tsx
  src/components/AppBarBottom/AppBarBottomVIew.tsx
  src/components/Badge/Badge.tsx
  src/components/Banner/ListBanner.tsx
  src/components/Icon/TrashcanIcon.tsx
  src/components/Icon/index.tsx
  src/components/ListItem/TwoLineListItem.tsx
  src/components/MissionDetail/MissionHistoryTab.tsx
  src/components/MissionDetail/MissionHistoryTabLayout.tsx
  src/components/MissionList/Badge.tsx
  src/components/MissionList/Empty.tsx
  src/components/MissionList/Item.tsx
  src/components/MissionList/LinkItem.tsx
  src/components/MissionList/ListContainer.tsx
  src/components/MissionList/NoticeEmpty.tsx
  src/components/MissionList/ReactionLinkItem.tsx
  src/components/MissionList/Skeleton.tsx
  src/components/MissionList/index.tsx
  src/components/ReactionBar/MyReactionBar/MyReactionBar.tsx
  src/components/ReactionBar/OtherReactionBar/OtherReactionBar.tsx
  src/components/ReactionBar/ReactionBottomSheet.tsx
  src/components/SnackBar/SnackBarOverlay.tsx
  src/constants/eventLog.ts
Labels: enhancement, deploy

#600 [Fix] QA 수정사항 반영
  public/images/banner/graphic-bg-gradient.svg
  src/app/auth/login/page.tsx
  src/app/result/OverallStatus/MissionList.tsx
  src/app/result/OverallStatus/MissionSection.tsx
  src/components/Banner/GraphicBanner.tsx
  src/components/MissionList/ReactionLinkItem.tsx
  src/components/Thumbnail/Thumbnail.tsx
Labels: bug fix, design
